# Generated by Django 5.2.1 on 2025-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('case_image', models.ImageField(blank=True, null=True, upload_to='caseimage/')),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('labour law', 'LABOUR LAW'), ('tax law', 'TAX LAW'), ('other', 'OTHER')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lawfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('years_of_exp', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('description', models.TextField()),
                ('advimg', models.ImageField(blank=True, null=True, upload_to='advimg/')),
            ],
        ),
    ]
