# Generated by Django 5.2.1 on 2025-06-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcases',
            name='case_image',
            field=models.ImageField(blank=True, null=True, upload_to='caseimg/'),
        ),
    ]
