# Generated by Django 5.2.1 on 2025-06-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0002_alter_allcases_case_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('labour law', 'LABOUR LAW'), ('tax law', 'TAX LAW'), ('other', 'OTHER')], max_length=100)),
                ('description', models.TextField()),
                ('case_doc', models.ImageField(blank=True, null=True, upload_to='advimg/')),
                ('total_no_hearings', models.BigIntegerField()),
                ('court_name', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('labour law', 'LABOUR LAW'), ('tax law', 'TAX LAW'), ('other', 'OTHER')], max_length=100)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='any_doc',
            field=models.ImageField(blank=True, null=True, upload_to='advimg/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
