# Generated by Django 5.2.1 on 2025-06-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0003_appointment_enquiry_any_doc_enquiry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='court_name',
            field=models.CharField(choices=[('high-court', 'HIGH-COURT'), ('supreme-court', 'SUPREME-COURT'), ('district-court', 'DISTRICT-COURT')], max_length=100),
        ),
    ]
