# Generated by Django 5.2.1 on 2025-06-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0004_alter_appointment_court_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='case_type',
            field=models.CharField(choices=[('criminal case', 'CRIMINAL CASE'), ('civil case', 'CIVIL CASE'), ('labour case', 'LABOUR CASE'), ('tax case', 'TAX CASE'), ('other', 'OTHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='case_type',
            field=models.CharField(choices=[('criminal case', 'CRIMINAL CASE'), ('civil case', 'CIVIL CASE'), ('labour case', 'LABOUR CASE'), ('tax case', 'TAX CASE'), ('other', 'OTHER')], max_length=100),
        ),
    ]
