# Generated by Django 5.2.1 on 2025-06-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btrapp', '0002_userprofile_delete_usermodel'),
        ('lawfirmapp', '0004_alter_appointment_court_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointemts', to='lawfirmapp.appointment')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawfirm', to='lawfirmapp.lawfirm')),
            ],
        ),
    ]
