# Generated by Django 5.2.1 on 2025-06-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btrapp', '0003_casemanagement'),
        ('lawfirmapp', '0004_alter_appointment_court_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemanagement',
            name='court',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enqueries', to='lawfirmapp.enquiry'),
            preserve_default=False,
        ),
    ]
